language: php

sudo: false

php:
- 5.4
- 5.5
- 5.6
- hhvm

env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.1 WP_MULTISITE=0
- WP_VERSION=4.0 WP_MULTISITE=0
- WP_VERSION=3.9.2 WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1
  exclude:
    - php: hhvm
      env: WP_VERSION=3.9.2 WP_MULTISITE=0
    - php: hhvm
      env: WP_VERSION=4.0 WP_MULTISITE=0

before_install:
  - git submodule update --init --recursive

install:
  - composer install

before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
- phpunit
