language: php
sudo: false

php:
- 5.4
- 5.5
- 5.6
- hhvm

env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.1 WP_MULTISITE=0
- WP_VERSION=4.0 WP_MULTISITE=0
- WP_VERSION=3.9.2 WP_MULTISITE=0

matrix:
  exclude:
  - php: hhvm
    env: WP_VERSION=3.9.2 WP_MULTISITE=0
  - php: hhvm
    env: WP_VERSION=4.0 WP_MULTISITE=0

before_install:
- git submodule update --init --recursive

install:
- composer install

before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
- phpunit

after_success:
- if [[ $TRAVIS_PHP_VERSION = '5.4' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
  ]]; bash bin/travis-deploy.sh; fi

notifications:
  slack:
    secure: HJRRU0ow1EpHxGxkVtT2WvG4Bbw+eeiJy4gACDOp1HmxXvWEH8BMziB8lP5l6Iv6MFcgExrMPFgsJI3PJgO8iTtrSyjebxahv4LFaU7uvoBwklIpeIcNyhg5DEoKenrsmmfwneArhn/1pQZOCrwSAxKqelp/G74AvFB7D/pcc3s=
