name: Release to WordPress.org
on:
  push:
    tags:
      - "*"
      - "!*-beta*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-20.04
    steps:
    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Build
      run: |
          make install_php_scoper
          make build
          npm install fs-extra
          node bin/workspace.js
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: podlove-podcasting-plugin-for-wordpress
